import { AspectKVData } from '@zodic/shared/types';

const mockAspectsData: AspectKVData[] = [
  {
    aspectingPlanet: 'moon',
    aspectedPlanet: 'mars',
    type: 'trine',
    orb: 3.42,
    diff: 123.42,
    report:
      '{"Introdução":[{"type":"p","content":"A Lua em trígono com Marte é um aspecto astrológico poderoso e harmonioso que conecta o reino emocional (Lua) com a energia da ação e do desejo (Marte). Este aspecto promove um fluxo natural entre sentimentos e motivação, permitindo que os indivíduos canalizem suas emoções em ações produtivas e assertivas."}],"Expressão Emocional e Confiança":[{"type":"p","content":"Com a Lua em trígono com Marte, as emoções são expressas com clareza e confiança. Há uma forte capacidade de se afirmar sem agressividade, pois as necessidades emocionais se alinham perfeitamente com o impulso de agir. Este aspecto frequentemente indica uma pessoa emocionalmente resiliente e capaz de enfrentar desafios com determinação."}],"Motivação e Energia":[{"type":"p","content":"Este aspecto proporciona um fluxo constante de energia e motivação. Indivíduos com essa configuração costumam ser proativos, capazes de perseguir seus objetivos com entusiasmo e foco. A conexão harmoniosa entre a Lua e Marte garante que as necessidades emocionais alimentem suas ambições em vez de atrapalhá-las."}],"Relacionamentos e Interações":[{"type":"p","content":"Nos relacionamentos, a Lua em trígono com Marte promove calor e paixão. Indivíduos com esse aspecto costumam ser solidários e protetores com seus entes queridos, expressando seu cuidado por meio de ações e não apenas de palavras. Eles também são habilidosos em resolver conflitos de maneira construtiva, pois sua inteligência emocional e assertividade trabalham em harmonia."}],"Desafios e Crescimento":[{"type":"p","content":"Embora a Lua em trígono com Marte seja predominantemente positiva, pode haver uma tendência a confiar excessivamente nesse talento natural, potencialmente negligenciando outras áreas de desenvolvimento pessoal. É importante que os indivíduos com esse aspecto equilibrem seu impulso emocional com introspecção e mindfulness."}],"Conclusão":[{"type":"p","content":"A Lua em trígono com Marte é um aspecto dinâmico e empoderador que aumenta a resiliência emocional, a motivação e a capacidade de tomar ações decisivas. É um dom que, quando usado com sabedoria, pode levar a um crescimento pessoal e relacional significativo."}]}',
  },
  {
    aspectingPlanet: 'moon',
    aspectedPlanet: 'uranus',
    type: 'square',
    orb: 4.01,
    diff: 94.01,
    report:
      '{"Introdução":[{"type":"p","content":"A Lua em quadratura com Urano é um aspecto astrológico intenso e dinâmico que traz agitação emocional, mudanças repentinas e um desejo por liberdade. Essa quadratura cria tensão entre a natureza emocional e nutridora da Lua e a energia rebelde e imprevisível de Urano. Frequentemente, ela desencadeia eventos inesperados na vida pessoal e emocional, levando os indivíduos a confrontar sua necessidade de estabilidade versus o anseio por independência."}],"Temas Principais":[{"type":"bullet-point","title":"Instabilidade Emocional","content":"A Lua rege as emoções, enquanto Urano as desafia e perturba. Essa quadratura pode levar a mudanças de humor, inquietação e uma sensação de imprevisibilidade emocional."},{"type":"bullet-point","title":"Desejo de Liberdade","content":"Urano incentiva a quebra de rotinas e dependências emocionais, frequentemente causando atritos em relacionamentos ou hábitos pessoais."},{"type":"bullet-point","title":"Mudanças Repentinas","content":"Esse aspecto está associado a eventos inesperados que podem abalar a base emocional de alguém, como términos abruptos ou novos começos surpreendentes."}],"Impacto nos Relacionamentos":[{"type":"p","content":"Nos relacionamentos, a Lua em quadratura com Urano pode criar uma dinâmica de vai e vem. Pode haver um conflito entre a necessidade de proximidade emocional e o desejo de independência. Os parceiros podem achar difícil atender às necessidades um do outro, levando a mal-entendidos ou separações repentinas. No entanto, esse aspecto também pode trazer excitação e inovação aos relacionamentos, incentivando o crescimento por meio da mudança."}],"Oportunidades de Crescimento Pessoal":[{"type":"p","content":"Embora desafiador, a Lua em quadratura com Urano oferece oportunidades de desenvolvimento pessoal. Ela encoraja os indivíduos a abraçar sua singularidade, libertar-se de padrões emocionais e adaptar-se à imprevisibilidade da vida. Aprender a equilibrar necessidades emocionais com o desejo de liberdade pode levar a uma maior autoconsciência e resiliência."}],"Conclusão":[{"type":"p","content":"A Lua em quadratura com Urano é um aspecto poderoso que testa a estabilidade emocional e a capacidade de adaptação. Ao abraçar sua energia, os indivíduos podem transformar desafios em oportunidades de crescimento, promovendo uma compreensão mais profunda de suas necessidades e desejos emocionais."}]}',
  },
  {
    aspectingPlanet: 'moon',
    aspectedPlanet: 'venus',
    type: 'square',
    orb: 6.74,
    diff: 83.26,
    report:
      '{"Visão Geral":[{"type":"p","content":"A Lua quadrado Vênus é um aspecto astrológico desafiador que destaca a tensão entre as necessidades emocionais (Lua) e os relacionamentos ou valores (Vênus). Esse aspecto frequentemente cria conflitos internos, pois o desejo por segurança emocional entra em choque com a busca por harmonia e afeto nos relacionamentos."}],"Dinâmicas Emocionais":[{"type":"p","content":"Sob esse aspecto, os indivíduos podem ter dificuldade em equilibrar suas necessidades emocionais com o desejo de agradar os outros. A Lua representa sentimentos profundos e instintos, enquanto Vênus governa o amor, a beleza e a harmonia social. Quando esses dois planetas formam um quadrado, pode haver uma sensação de insatisfação ou insegurança nos relacionamentos. As necessidades emocionais podem parecer não atendidas, levando a frustrações ou mudanças de humor."}],"Desafios nos Relacionamentos":[{"type":"p","content":"Nos relacionamentos, a Lua quadrado Vênus pode se manifestar como dificuldade em expressar afeto ou se sentir apreciado. Pode haver uma tendência a buscar validação dos outros enquanto simultaneamente se sente indigno de amor. Esse aspecto também pode indicar uma incompatibilidade entre as expectativas emocionais e a realidade, levando a mal-entendidos ou distanciamento emocional."}],"Crescimento Pessoal":[{"type":"p","content":"Embora esse aspecto possa ser desafiador, ele também oferece oportunidades de crescimento. Ao se tornarem conscientes de seus padrões emocionais e aprenderem a comunicar suas necessidades de forma mais eficaz, os indivíduos podem transformar essa tensão em um entendimento mais profundo de si mesmos e de seus relacionamentos. Autocompaixão e autocuidado são essenciais para navegar esse aspecto com sucesso."}],"Conselhos Práticos":[{"type":"bullet-point","content":"Reflita sobre suas necessidades emocionais e comunique-as claramente ao seu parceiro ou entes queridos."},{"type":"bullet-point","content":"Evite buscar validação externa; concentre-se em construir sua autoestima internamente."},{"type":"bullet-point","content":"Pratique o autocuidado para nutrir seu bem-estar emocional."},{"type":"bullet-point","content":"Esteja atento às tendências de compensar excessivamente nos relacionamentos ou de suprimir seus sentimentos."}]}',
  },
  {
    aspectingPlanet: 'sun',
    aspectedPlanet: 'venus',
    type: 'conjunction',
    orb: 9.56,
    diff: 9.56,
    report:
      '{"Introdução":[{"type":"p","content":"A conjunção entre o Sol e Vênus é um aspecto astrológico harmonioso e poderoso que combina as energias do eu (Sol) e do amor, beleza e relacionamentos (Vênus). Esta conjunção frequentemente simboliza um período de positividade, charme e criatividade aprimorada na vida de um indivíduo. É um momento em que o magnetismo pessoal é amplificado e os relacionamentos tendem a florescer."}],"Características Principais":[{"type":"p","content":"Quando o Sol e Vênus se alinham, os seguintes traços são frequentemente destacados:"},{"type":"bullet-point","title":"Charme e Atraência Aumentados","content":"Indivíduos com este aspecto irradiam calor e simpatia, facilitando a conexão com os outros."},{"type":"bullet-point","title":"Expressão Artística e Criativa","content":"Esta conjunção promove uma forte apreciação pela beleza e frequentemente inspira empreendimentos artísticos."},{"type":"bullet-point","title":"Harmonia nos Relacionamentos","content":"Ela promove cooperação, afeto e compreensão mútua em relacionamentos pessoais e profissionais."},{"type":"bullet-point","title":"Autoestima e Confiança","content":"A energia do Sol amplifica a influência de Vênus, aumentando a autoestima e o senso de valor pessoal."}],"Impacto na Vida Pessoal":[{"type":"p","content":"Nos relacionamentos pessoais, a conjunção Sol-Vênus traz uma sensação de facilidade e alegria. Parcerias são frequentemente marcadas por admiração mútua e um desejo de criar harmonia. Solteiros podem achar este período particularmente favorável para atrair interesses românticos."}],"Impacto na Carreira e Criatividade":[{"type":"p","content":"Profissionalmente, este aspecto encoraja colaboração e diplomacia. É um excelente momento para projetos criativos, já que o alinhamento aprimora a visão artística e a habilidade de expressar ideias de forma bela. Aqueles em campos como arte, design ou relações públicas podem achar seu trabalho particularmente recompensador durante esta fase."}],"Desafios e Considerações":[{"type":"p","content":"Embora este aspecto seja geralmente positivo, ele pode às vezes levar a excessos em prazeres ou uma tendência a evitar conflitos. É importante manter o equilíbrio e não deixar que o desejo por harmonia sobreponha a assertividade necessária."}],"Conclusão":[{"type":"p","content":"A conjunção Sol-Vênus é um aspecto fortuito que traz alegria, criatividade e conexão. Ao abraçar suas energias, os indivíduos podem aprimorar seus relacionamentos, expressar sua criatividade e cultivar um senso mais profundo de autoestima."}]}',
  },
  {
    aspectingPlanet: 'moon',
    aspectedPlanet: 'mercury',
    type: 'square',
    orb: 4.03,
    diff: 94.03,
    report:
      '{"Visão Geral":[{"type":"p","content":"A Lua em quadratura com Mercúrio é um aspecto astrológico desafiador que evidencia a tensão entre emoções e comunicação. Esse aspecto ocorre quando a Lua e Mercúrio estão a 90 graus de distância, criando uma dinâmica que pode levar a mal-entendidos, sobrecarga emocional e dificuldade em expressar sentimentos com clareza."}],"Temas Principais":[{"type":"bullet-point","title":"Conflito Emocional vs. Intelectual","content":"Esse aspecto frequentemente cria um vai-e-vem entre necessidades emocionais e raciocínio lógico. Indivíduos podem lutar para equilibrar seus sentimentos com o pensamento racional."},{"type":"bullet-point","title":"Desafios na Comunicação","content":"A má comunicação é um problema comum. As palavras podem sair erradas, ou as emoções podem turvar a mensagem, levando à frustração."},{"type":"bullet-point","title":"Inquietação Interna","content":"Pode haver uma sensação de agitação mental, pois a mente corre para processar emoções, mas luta para encontrar clareza."}],"Pontos Fortes":[{"type":"bullet-point","title":"Consciência Aumentada","content":"Esse aspecto pode tornar os indivíduos mais perceptivos em relação às suas próprias emoções e às emoções dos outros."},{"type":"bullet-point","title":"Solução Criativa de Problemas","content":"A tensão pode estimular o pensamento inovador, especialmente ao buscar maneiras de unir lacunas emocionais e intelectuais."}],"Desafios":[{"type":"bullet-point","title":"Pensamento Excessivo","content":"A mente pode se tornar excessivamente analítica, levando à ansiedade ou indecisão."},{"type":"bullet-point","title":"Sensibilidade Emocional","content":"Indivíduos podem se sentir facilmente magoados ou mal compreendidos, principalmente em conversas."}],"Como Navegar Esse Aspecto":[{"type":"bullet-point","title":"Pratique Comunicação Consciente","content":"Reserve um tempo para refletir sobre as emoções antes de falar. Isso pode reduzir mal-entendidos."},{"type":"bullet-point","title":"Diário","content":"Escrever pensamentos e sentimentos pode ajudar a processar emoções e clarear a mente."},{"type":"bullet-point","title":"Busque Equilíbrio","content":"Esforce-se para integrar perspectivas emocionais e intelectuais, em vez de deixar uma dominar."}],"Conclusão":[{"type":"p","content":"Embora a Lua em quadratura com Mercúrio possa ser um aspecto desafiador, ele também oferece oportunidades de crescimento. Ao aprender a navegar a tensão entre emoções e comunicação, os indivíduos podem desenvolver maior autoconsciência e melhorar seus relacionamentos."}]}',
  },
  {
    aspectingPlanet: 'sun',
    aspectedPlanet: 'jupiter',
    type: 'trine',
    orb: 4.72,
    diff: 124.72,
    report:
      '{"Introdução":[{"type":"p","content":"O Sol trígono Júpiter é um aspecto astrológico altamente favorável que traz uma sensação de harmonia, otimismo e crescimento. Este aspecto ocorre quando o Sol e Júpiter estão separados por 120 graus, formando um trígono, considerado uma das configurações mais benéficas na astrologia. Ele simboliza o alinhamento da identidade central do indivíduo (Sol) com seu senso de propósito, abundância e expansão (Júpiter)."}],"Temas Principais do Sol Trígono Júpiter":[{"type":"bullet-point","title":"Abundância e Oportunidade","content":"Este aspecto frequentemente traz oportunidades de crescimento, seja no desenvolvimento pessoal, na carreira ou nos relacionamentos."},{"type":"bullet-point","title":"Otimismo e Confiança","content":"Indivíduos com este aspecto tendem a ter uma visão positiva da vida e uma forte crença em suas habilidades."},{"type":"bullet-point","title":"Generosidade e Filantropia","content":"Há uma inclinação natural para compartilhar suas bênçãos com os outros, frequentemente levando a atos de bondade e generosidade."},{"type":"bullet-point","title":"Sorte e Sucesso","content":"A influência de Júpiter traz um toque de sorte, facilitando a conquista de objetivos e a superação de desafios."}],"Como Se Manifesta na Vida":[{"type":"bullet-point","title":"Carreira e Ambições","content":"Este aspecto apoia o avanço na carreira e o reconhecimento, frequentemente através de trabalho duro e uma atitude positiva."},{"type":"bullet-point","title":"Crescimento Pessoal","content":"Ele incentiva o autodesenvolvimento e o desejo de aprender, frequentemente levando a um aumento da sabedoria e do entendimento."},{"type":"bullet-point","title":"Relacionamentos","content":"Ele promove relacionamentos harmoniosos, pois indivíduos com este aspecto são frequentemente calorosos, generosos e fáceis de conviver."}],"Desafios e Equilíbrio":[{"type":"p","content":"Embora o Sol trígono Júpiter seja predominantemente positivo, há um risco de excesso de confiança ou de tomar as coisas como garantidas. É importante permanecer com os pés no chão e evitar tornar-se complacente."}],"Conclusão":[{"type":"p","content":"O Sol trígono Júpiter é um aspecto poderoso que aumenta o otimismo, o crescimento e o sucesso. Ao abraçar sua energia, os indivíduos podem desbloquear seu potencial máximo e criar uma vida cheia de abundância e alegria."}]}',
  },
  {
    aspectingPlanet: 'moon',
    aspectedPlanet: 'ascendant',
    type: 'trine',
    orb: 1.77,
    diff: 118.23,
    report:
      '{"Visão Geral":[{"type":"p","content":"A Lua em trígono com o Ascendente é um aspecto astrológico harmonioso que destaca o equilíbrio emocional, a compreensão intuitiva e a habilidade natural de se conectar com os outros. Esse aspecto cria um fluxo suave de energia entre a Lua, que representa as emoções e o eu interior, e o Ascendente, que governa a personalidade, a aparência e as primeiras impressões."}],"Expressão Emocional":[{"type":"p","content":"Indivíduos com esse aspecto são frequentemente emocionalmente sintonizados com seu entorno. Eles têm uma capacidade natural de expressar seus sentimentos de uma maneira que ressoa com os outros, tornando-os acessíveis e empáticos. Sua inteligência emocional é alta, permitindo que naveguem em situações sociais com facilidade e graça."}],"Relacionamentos e Interações":[{"type":"p","content":"Pessoas com a Lua em trígono com o Ascendente são frequentemente vistas como nutridoras e solidárias. Elas têm um talento para fazer os outros se sentirem confortáveis e compreendidos. Nos relacionamentos, são parceiros atenciosos e cuidadosos que priorizam a conexão emocional e o entendimento mútuo."}],"Autoimagem e Confiança":[{"type":"p","content":"Esse aspecto também influencia positivamente a autoimagem. Esses indivíduos tendem a ter um senso saudável de autoestima e confiança. Eles estão confortáveis em sua própria pele e projetam uma sensação de paz interior e estabilidade, o que pode ser muito atraente para os outros."}],"Desafios e Crescimento":[{"type":"p","content":"Embora a Lua em trígono com o Ascendente seja geralmente um aspecto benéfico, às vezes pode levar a uma dependência excessiva da intuição emocional. Os indivíduos podem precisar equilibrar suas respostas emocionais com o pensamento lógico para evitar se tornarem excessivamente sensíveis ou dependentes da aprovação dos outros."}],"Conclusão":[{"type":"p","content":"A Lua em trígono com o Ascendente é um aspecto poderoso que promove harmonia emocional, fortes conexões interpessoais e uma autoimagem positiva. Ao abraçar sua natureza intuitiva enquanto mantêm uma abordagem equilibrada em relação às emoções, os indivíduos com esse aspecto podem prosperar tanto no âmbito pessoal quanto no social."}]}',
  },
  {
    aspectingPlanet: 'jupiter',
    aspectedPlanet: 'pluto',
    type: 'square',
    orb: 5.46,
    diff: 95.46,
    report: null,
  },
  {
    aspectingPlanet: 'mercury',
    aspectedPlanet: 'neptune',
    type: 'conjunction',
    orb: 4.85,
    diff: 4.85,
    report:
      '{"Visão Geral":[{"type":"p","content":"A conjunção Mercúrio-Netuno é um aspecto astrológico fascinante que combina as energias da comunicação (Mercúrio) e da intuição, imaginação e espiritualidade (Netuno). Esse alinhamento cria uma interação única entre lógica e criatividade, muitas vezes ampliando a expressão artística, a empatia e a sensibilidade psíquica. No entanto, também pode trazer desafios, como confusão, má comunicação ou uma tendência a escapar da realidade."}],"Temas Principais":[{"type":"bullet-point","title":"Imaginação e Criatividade Aprimoradas","content":"Esse aspecto amplia as habilidades criativas, tornando-o um excelente momento para atividades artísticas, escrita ou qualquer forma de expressão pessoal."},{"type":"bullet-point","title":"Comunicação Intuitiva","content":"Mercúrio conjunção Netuno pode aumentar a intuição, permitindo que os indivíduos percebam sinais sutis e se comuniquem com empatia e sensibilidade."},{"type":"bullet-point","title":"Potencial para Confusão","content":"A mistura da lógica de Mercúrio com o sonho de Netuno pode levar a mal-entendidos, pensamentos vagos ou dificuldade em distinguir fato de ficção."},{"type":"bullet-point","title":"Insights Espirituais","content":"Essa conjunção frequentemente promove uma conexão mais profunda com a espiritualidade, meditação ou experiências místicas."}],"Manifestações Positivas":[{"type":"bullet-point","title":"Inspiração Artística","content":"Escritores, artistas e músicos podem encontrar seu trabalho impregnado de ideias profundas e imaginativas."},{"type":"bullet-point","title":"Empatia e Compaixão","content":"As conversas se tornam mais sinceras, e os indivíduos podem se sentir mais sintonizados com as emoções dos outros."},{"type":"bullet-point","title":"Sensibilidade Psíquica","content":"A intuição aumentada pode levar a sonhos proféticos, fortes intuições ou revelações espirituais."}],"Desafios a Considerar":[{"type":"bullet-point","title":"Má Comunicação","content":"As mensagens podem ser pouco claras ou mal interpretadas, levando a confusão em relacionamentos pessoais ou profissionais."},{"type":"bullet-point","title":"Evasão","content":"O desejo de se refugiar em um mundo de fantasia pode se tornar avassalador, potencialmente negligenciando responsabilidades."},{"type":"bullet-point","title":"Engano","content":"Esse aspecto pode aumentar a suscetibilidade a enganos, seja de outras pessoas ou de autoengano."}],"Conselhos Práticos":[{"type":"bullet-point","title":"Clarifique as Intenções","content":"Esteja atento à sua comunicação, garantindo que sua mensagem seja clara e compreendida."},{"type":"bullet-point","title":"Aterre-se","content":"Pratique atividades de aterramento, como meditação ou passar tempo na natureza, para permanecer conectado à realidade."},{"type":"bullet-point","title":"Canalize a Criatividade","content":"Use essa energia de forma construtiva, engajando-se em atividades artísticas ou espirituais que o inspirem."}],"Conclusão":[{"type":"p","content":"A conjunção Mercúrio-Netuno é um aspecto poderoso que une os domínios da lógica e da intuição. Embora ofereça um potencial criativo e espiritual imenso, também exige atenção para superar seus desafios. Ao abraçar seus presentes e permanecer aterrado, esse alinhamento pode levar a um profundo crescimento pessoal e inspiração."}]}',
  },
  {
    aspectingPlanet: 'mercury',
    aspectedPlanet: 'uranus',
    type: 'conjunction',
    orb: 0.02,
    diff: 0.02,
    report:
      '{"Visão Geral":[{"type":"p","content":"A conjunção entre Mercúrio e Urano é um aspecto astrológico poderoso que une as características analíticas e comunicativas de Mercúrio com a energia revolucionária e imprevisível de Urano. Esse alinhamento estimula um período de intensa atividade mental, originalidade e pensamento não convencional, trazendo insights repentinos, avanços e um desejo de liberdade intelectual."}],"Temas Principais":[{"type":"bullet-point","title":"Agilidade Mental e Inovação","content":"Esse aspecto estimula a mente, incentivando ideias inovadoras e soluções criativas para problemas. É um momento em que pensar fora da caixa se torna natural, e métodos convencionais podem parecer limitantes."},{"type":"bullet-point","title":"Comunicação Imprevisível","content":"A comunicação pode se tornar errática ou repentina, com uma tendência a expressar ideias não convencionais ou radicais. Isso pode levar a trocas emocionantes, mas também pode causar mal-entendidos se não for equilibrada com clareza."},{"type":"bullet-point","title":"Foco em Tecnologia e Ciência","content":"Urano rege a tecnologia e o progresso, então essa conjunção frequentemente destaca avanços nessas áreas. É um momento favorável para explorar novas tecnologias, descobertas científicas ou inovações digitais."},{"type":"bullet-point","title":"Liberdade de Pensamento","content":"Há um forte desejo de independência intelectual e liberdade das restrições tradicionais. As pessoas podem se sentir compelidas a desafiar normas, questionar autoridades ou adotar pontos de vista progressistas."}],"Impacto nos Indivíduos":[{"type":"p","content":"Para os indivíduos, essa conjunção pode se manifestar como uma explosão repentina de inspiração ou uma necessidade de romper com a rotina. É um momento para abraçar mudanças, experimentar novas ideias e se comunicar com ousadia. No entanto, é importante permanecer centrado para evitar impulsividade ou pensamento disperso."}],"Impacto nos Relacionamentos":[{"type":"p","content":"Nos relacionamentos, esse aspecto pode trazer conversas emocionantes e inesperadas. Os parceiros podem se sentir mais abertos para discutir tópicos não convencionais ou explorar novas formas de conexão. No entanto, tensões podem surgir se as ideias de uma pessoa parecerem muito radicais ou imprevisíveis para a outra."}],"Dicas para Aproveitar Essa Energia":[{"type":"bullet-point","content":"Abrace a curiosidade e explore novas ideias."},{"type":"bullet-point","content":"Esteja aberto a insights repentinos ou mudanças de perspectiva."},{"type":"bullet-point","content":"Comunique-se com clareza para evitar mal-entendidos."},{"type":"bullet-point","content":"Use a tecnologia ou ferramentas inovadoras para aumentar a produtividade."}],"Conclusão":[{"type":"p","content":"A conjunção entre Mercúrio e Urano é um aspecto dinâmico e transformador que incentiva a liberdade intelectual, a inovação e o progresso. Ao abraçar sua energia, você pode desbloquear novas possibilidades e expandir seus horizontes."}]}',
  },
  {
    aspectingPlanet: 'mars',
    aspectedPlanet: 'saturn',
    type: 'trine',
    orb: 7.76,
    diff: 127.76,
    report: null,
  },
  {
    aspectingPlanet: 'mars',
    aspectedPlanet: 'ascendant',
    type: 'trine',
    orb: 1.65,
    diff: 118.35,
    report: null,
  },
  {
    aspectingPlanet: 'venus',
    aspectedPlanet: 'midheaven',
    type: 'sextile',
    orb: 0.31,
    diff: 59.69,
    report: null,
  },
  {
    aspectingPlanet: 'uranus',
    aspectedPlanet: 'neptune',
    type: 'conjunction',
    orb: 4.87,
    diff: 4.87,
    report: null,
  },
  {
    aspectingPlanet: 'saturn',
    aspectedPlanet: 'neptune',
    type: 'conjunction',
    orb: 9.95,
    diff: 9.95,
    report: null,
  },
  {
    aspectingPlanet: 'saturn',
    aspectedPlanet: 'midheaven',
    type: 'square',
    orb: 4.75,
    diff: 85.25,
    report: null,
  },
  {
    aspectingPlanet: 'saturn',
    aspectedPlanet: 'ascendant',
    type: 'conjunction',
    orb: 9.41,
    diff: 9.41,
    report: null,
  },
  {
    aspectingPlanet: 'saturn',
    aspectedPlanet: 'pluto',
    type: 'sextile',
    orb: 4.39,
    diff: 64.39,
    report: null,
  },
  {
    aspectingPlanet: 'neptune',
    aspectedPlanet: 'pluto',
    type: 'sextile',
    orb: 5.56,
    diff: 54.44,
    report: null,
  },
  {
    aspectingPlanet: 'ascendant',
    aspectedPlanet: 'midheaven',
    type: 'square',
    orb: 4.66,
    diff: 94.66,
    report: null,
  },
  {
    aspectingPlanet: 'moon',
    aspectedPlanet: 'venus',
    type: 'square',
    orb: 6.74,
    diff: 83.26,
    report:
      '{"Visão Geral":[{"type":"p","content":"A Lua quadrado Vênus é um aspecto astrológico desafiador que destaca a tensão entre as necessidades emocionais (Lua) e os relacionamentos ou valores (Vênus). Esse aspecto frequentemente cria conflitos internos, pois o desejo por segurança emocional entra em choque com a busca por harmonia e afeto nos relacionamentos."}],"Dinâmicas Emocionais":[{"type":"p","content":"Sob esse aspecto, os indivíduos podem ter dificuldade em equilibrar suas necessidades emocionais com o desejo de agradar os outros. A Lua representa sentimentos profundos e instintos, enquanto Vênus governa o amor, a beleza e a harmonia social. Quando esses dois planetas formam um quadrado, pode haver uma sensação de insatisfação ou insegurança nos relacionamentos. As necessidades emocionais podem parecer não atendidas, levando a frustrações ou mudanças de humor."}],"Desafios nos Relacionamentos":[{"type":"p","content":"Nos relacionamentos, a Lua quadrado Vênus pode se manifestar como dificuldade em expressar afeto ou se sentir apreciado. Pode haver uma tendência a buscar validação dos outros enquanto simultaneamente se sente indigno de amor. Esse aspecto também pode indicar uma incompatibilidade entre as expectativas emocionais e a realidade, levando a mal-entendidos ou distanciamento emocional."}],"Crescimento Pessoal":[{"type":"p","content":"Embora esse aspecto possa ser desafiador, ele também oferece oportunidades de crescimento. Ao se tornarem conscientes de seus padrões emocionais e aprenderem a comunicar suas necessidades de forma mais eficaz, os indivíduos podem transformar essa tensão em um entendimento mais profundo de si mesmos e de seus relacionamentos. Autocompaixão e autocuidado são essenciais para navegar esse aspecto com sucesso."}],"Conselhos Práticos":[{"type":"bullet-point","content":"Reflita sobre suas necessidades emocionais e comunique-as claramente ao seu parceiro ou entes queridos."},{"type":"bullet-point","content":"Evite buscar validação externa; concentre-se em construir sua autoestima internamente."},{"type":"bullet-point","content":"Pratique o autocuidado para nutrir seu bem-estar emocional."},{"type":"bullet-point","content":"Esteja atento às tendências de compensar excessivamente nos relacionamentos ou de suprimir seus sentimentos."}]}',
  },
  {
    aspectingPlanet: 'sun',
    aspectedPlanet: 'venus',
    type: 'conjunction',
    orb: 9.56,
    diff: 9.56,
    report:
      '{"Introdução":[{"type":"p","content":"A conjunção entre o Sol e Vênus é um aspecto astrológico harmonioso e poderoso que combina as energias do eu (Sol) e do amor, beleza e relacionamentos (Vênus). Esta conjunção frequentemente simboliza um período de positividade, charme e criatividade aprimorada na vida de um indivíduo. É um momento em que o magnetismo pessoal é amplificado e os relacionamentos tendem a florescer."}],"Características Principais":[{"type":"p","content":"Quando o Sol e Vênus se alinham, os seguintes traços são frequentemente destacados:"},{"type":"bullet-point","title":"Charme e Atraência Aumentados","content":"Indivíduos com este aspecto irradiam calor e simpatia, facilitando a conexão com os outros."},{"type":"bullet-point","title":"Expressão Artística e Criativa","content":"Esta conjunção promove uma forte apreciação pela beleza e frequentemente inspira empreendimentos artísticos."},{"type":"bullet-point","title":"Harmonia nos Relacionamentos","content":"Ela promove cooperação, afeto e compreensão mútua em relacionamentos pessoais e profissionais."},{"type":"bullet-point","title":"Autoestima e Confiança","content":"A energia do Sol amplifica a influência de Vênus, aumentando a autoestima e o senso de valor pessoal."}],"Impacto na Vida Pessoal":[{"type":"p","content":"Nos relacionamentos pessoais, a conjunção Sol-Vênus traz uma sensação de facilidade e alegria. Parcerias são frequentemente marcadas por admiração mútua e um desejo de criar harmonia. Solteiros podem achar este período particularmente favorável para atrair interesses românticos."}],"Impacto na Carreira e Criatividade":[{"type":"p","content":"Profissionalmente, este aspecto encoraja colaboração e diplomacia. É um excelente momento para projetos criativos, já que o alinhamento aprimora a visão artística e a habilidade de expressar ideias de forma bela. Aqueles em campos como arte, design ou relações públicas podem achar seu trabalho particularmente recompensador durante esta fase."}],"Desafios e Considerações":[{"type":"p","content":"Embora este aspecto seja geralmente positivo, ele pode às vezes levar a excessos em prazeres ou uma tendência a evitar conflitos. É importante manter o equilíbrio e não deixar que o desejo por harmonia sobreponha a assertividade necessária."}],"Conclusão":[{"type":"p","content":"A conjunção Sol-Vênus é um aspecto fortuito que traz alegria, criatividade e conexão. Ao abraçar suas energias, os indivíduos podem aprimorar seus relacionamentos, expressar sua criatividade e cultivar um senso mais profundo de autoestima."}]}',
  },
  {
    aspectingPlanet: 'moon',
    aspectedPlanet: 'mars',
    type: 'trine',
    orb: 3.42,
    diff: 123.42,
    report:
      '{"Introdução":[{"type":"p","content":"A Lua em trígono com Marte é um aspecto astrológico poderoso e harmonioso que conecta o reino emocional (Lua) com a energia da ação e do desejo (Marte). Este aspecto promove um fluxo natural entre sentimentos e motivação, permitindo que os indivíduos canalizem suas emoções em ações produtivas e assertivas."}],"Expressão Emocional e Confiança":[{"type":"p","content":"Com a Lua em trígono com Marte, as emoções são expressas com clareza e confiança. Há uma forte capacidade de se afirmar sem agressividade, pois as necessidades emocionais se alinham perfeitamente com o impulso de agir. Este aspecto frequentemente indica uma pessoa emocionalmente resiliente e capaz de enfrentar desafios com determinação."}],"Motivação e Energia":[{"type":"p","content":"Este aspecto proporciona um fluxo constante de energia e motivação. Indivíduos com essa configuração costumam ser proativos, capazes de perseguir seus objetivos com entusiasmo e foco. A conexão harmoniosa entre a Lua e Marte garante que as necessidades emocionais alimentem suas ambições em vez de atrapalhá-las."}],"Relacionamentos e Interações":[{"type":"p","content":"Nos relacionamentos, a Lua em trígono com Marte promove calor e paixão. Indivíduos com esse aspecto costumam ser solidários e protetores com seus entes queridos, expressando seu cuidado por meio de ações e não apenas de palavras. Eles também são habilidosos em resolver conflitos de maneira construtiva, pois sua inteligência emocional e assertividade trabalham em harmonia."}],"Desafios e Crescimento":[{"type":"p","content":"Embora a Lua em trígono com Marte seja predominantemente positiva, pode haver uma tendência a confiar excessivamente nesse talento natural, potencialmente negligenciando outras áreas de desenvolvimento pessoal. É importante que os indivíduos com esse aspecto equilibrem seu impulso emocional com introspecção e mindfulness."}],"Conclusão":[{"type":"p","content":"A Lua em trígono com Marte é um aspecto dinâmico e empoderador que aumenta a resiliência emocional, a motivação e a capacidade de tomar ações decisivas. É um dom que, quando usado com sabedoria, pode levar a um crescimento pessoal e relacional significativo."}]}',
  },
  {
    aspectingPlanet: 'sun',
    aspectedPlanet: 'jupiter',
    type: 'trine',
    orb: 4.72,
    diff: 124.72,
    report:
      '{"Introdução":[{"type":"p","content":"O Sol trígono Júpiter é um aspecto astrológico altamente favorável que traz uma sensação de harmonia, otimismo e crescimento. Este aspecto ocorre quando o Sol e Júpiter estão separados por 120 graus, formando um trígono, considerado uma das configurações mais benéficas na astrologia. Ele simboliza o alinhamento da identidade central do indivíduo (Sol) com seu senso de propósito, abundância e expansão (Júpiter)."}],"Temas Principais do Sol Trígono Júpiter":[{"type":"bullet-point","title":"Abundância e Oportunidade","content":"Este aspecto frequentemente traz oportunidades de crescimento, seja no desenvolvimento pessoal, na carreira ou nos relacionamentos."},{"type":"bullet-point","title":"Otimismo e Confiança","content":"Indivíduos com este aspecto tendem a ter uma visão positiva da vida e uma forte crença em suas habilidades."},{"type":"bullet-point","title":"Generosidade e Filantropia","content":"Há uma inclinação natural para compartilhar suas bênçãos com os outros, frequentemente levando a atos de bondade e generosidade."},{"type":"bullet-point","title":"Sorte e Sucesso","content":"A influência de Júpiter traz um toque de sorte, facilitando a conquista de objetivos e a superação de desafios."}],"Como Se Manifesta na Vida":[{"type":"bullet-point","title":"Carreira e Ambições","content":"Este aspecto apoia o avanço na carreira e o reconhecimento, frequentemente através de trabalho duro e uma atitude positiva."},{"type":"bullet-point","title":"Crescimento Pessoal","content":"Ele incentiva o autodesenvolvimento e o desejo de aprender, frequentemente levando a um aumento da sabedoria e do entendimento."},{"type":"bullet-point","title":"Relacionamentos","content":"Ele promove relacionamentos harmoniosos, pois indivíduos com este aspecto são frequentemente calorosos, generosos e fáceis de conviver."}],"Desafios e Equilíbrio":[{"type":"p","content":"Embora o Sol trígono Júpiter seja predominantemente positivo, há um risco de excesso de confiança ou de tomar as coisas como garantidas. É importante permanecer com os pés no chão e evitar tornar-se complacente."}],"Conclusão":[{"type":"p","content":"O Sol trígono Júpiter é um aspecto poderoso que aumenta o otimismo, o crescimento e o sucesso. Ao abraçar sua energia, os indivíduos podem desbloquear seu potencial máximo e criar uma vida cheia de abundância e alegria."}]}',
  },
  {
    aspectingPlanet: 'moon',
    aspectedPlanet: 'mercury',
    type: 'square',
    orb: 4.03,
    diff: 94.03,
    report:
      '{"Visão Geral":[{"type":"p","content":"A Lua em quadratura com Mercúrio é um aspecto astrológico desafiador que evidencia a tensão entre emoções e comunicação. Esse aspecto ocorre quando a Lua e Mercúrio estão a 90 graus de distância, criando uma dinâmica que pode levar a mal-entendidos, sobrecarga emocional e dificuldade em expressar sentimentos com clareza."}],"Temas Principais":[{"type":"bullet-point","title":"Conflito Emocional vs. Intelectual","content":"Esse aspecto frequentemente cria um vai-e-vem entre necessidades emocionais e raciocínio lógico. Indivíduos podem lutar para equilibrar seus sentimentos com o pensamento racional."},{"type":"bullet-point","title":"Desafios na Comunicação","content":"A má comunicação é um problema comum. As palavras podem sair erradas, ou as emoções podem turvar a mensagem, levando à frustração."},{"type":"bullet-point","title":"Inquietação Interna","content":"Pode haver uma sensação de agitação mental, pois a mente corre para processar emoções, mas luta para encontrar clareza."}],"Pontos Fortes":[{"type":"bullet-point","title":"Consciência Aumentada","content":"Esse aspecto pode tornar os indivíduos mais perceptivos em relação às suas próprias emoções e às emoções dos outros."},{"type":"bullet-point","title":"Solução Criativa de Problemas","content":"A tensão pode estimular o pensamento inovador, especialmente ao buscar maneiras de unir lacunas emocionais e intelectuais."}],"Desafios":[{"type":"bullet-point","title":"Pensamento Excessivo","content":"A mente pode se tornar excessivamente analítica, levando à ansiedade ou indecisão."},{"type":"bullet-point","title":"Sensibilidade Emocional","content":"Indivíduos podem se sentir facilmente magoados ou mal compreendidos, principalmente em conversas."}],"Como Navegar Esse Aspecto":[{"type":"bullet-point","title":"Pratique Comunicação Consciente","content":"Reserve um tempo para refletir sobre as emoções antes de falar. Isso pode reduzir mal-entendidos."},{"type":"bullet-point","title":"Diário","content":"Escrever pensamentos e sentimentos pode ajudar a processar emoções e clarear a mente."},{"type":"bullet-point","title":"Busque Equilíbrio","content":"Esforce-se para integrar perspectivas emocionais e intelectuais, em vez de deixar uma dominar."}],"Conclusão":[{"type":"p","content":"Embora a Lua em quadratura com Mercúrio possa ser um aspecto desafiador, ele também oferece oportunidades de crescimento. Ao aprender a navegar a tensão entre emoções e comunicação, os indivíduos podem desenvolver maior autoconsciência e melhorar seus relacionamentos."}]}',
  },
  {
    aspectingPlanet: 'moon',
    aspectedPlanet: 'uranus',
    type: 'square',
    orb: 4.01,
    diff: 94.01,
    report:
      '{"Introdução":[{"type":"p","content":"A Lua em quadratura com Urano é um aspecto astrológico intenso e dinâmico que traz agitação emocional, mudanças repentinas e um desejo por liberdade. Essa quadratura cria tensão entre a natureza emocional e nutridora da Lua e a energia rebelde e imprevisível de Urano. Frequentemente, ela desencadeia eventos inesperados na vida pessoal e emocional, levando os indivíduos a confrontar sua necessidade de estabilidade versus o anseio por independência."}],"Temas Principais":[{"type":"bullet-point","title":"Instabilidade Emocional","content":"A Lua rege as emoções, enquanto Urano as desafia e perturba. Essa quadratura pode levar a mudanças de humor, inquietação e uma sensação de imprevisibilidade emocional."},{"type":"bullet-point","title":"Desejo de Liberdade","content":"Urano incentiva a quebra de rotinas e dependências emocionais, frequentemente causando atritos em relacionamentos ou hábitos pessoais."},{"type":"bullet-point","title":"Mudanças Repentinas","content":"Esse aspecto está associado a eventos inesperados que podem abalar a base emocional de alguém, como términos abruptos ou novos começos surpreendentes."}],"Impacto nos Relacionamentos":[{"type":"p","content":"Nos relacionamentos, a Lua em quadratura com Urano pode criar uma dinâmica de vai e vem. Pode haver um conflito entre a necessidade de proximidade emocional e o desejo de independência. Os parceiros podem achar difícil atender às necessidades um do outro, levando a mal-entendidos ou separações repentinas. No entanto, esse aspecto também pode trazer excitação e inovação aos relacionamentos, incentivando o crescimento por meio da mudança."}],"Oportunidades de Crescimento Pessoal":[{"type":"p","content":"Embora desafiador, a Lua em quadratura com Urano oferece oportunidades de desenvolvimento pessoal. Ela encoraja os indivíduos a abraçar sua singularidade, libertar-se de padrões emocionais e adaptar-se à imprevisibilidade da vida. Aprender a equilibrar necessidades emocionais com o desejo de liberdade pode levar a uma maior autoconsciência e resiliência."}],"Conclusão":[{"type":"p","content":"A Lua em quadratura com Urano é um aspecto poderoso que testa a estabilidade emocional e a capacidade de adaptação. Ao abraçar sua energia, os indivíduos podem transformar desafios em oportunidades de crescimento, promovendo uma compreensão mais profunda de suas necessidades e desejos emocionais."}]}',
  },
  {
    aspectingPlanet: 'moon',
    aspectedPlanet: 'ascendant',
    type: 'trine',
    orb: 1.77,
    diff: 118.23,
    report:
      '{"Visão Geral":[{"type":"p","content":"A Lua em trígono com o Ascendente é um aspecto astrológico harmonioso que destaca o equilíbrio emocional, a compreensão intuitiva e a habilidade natural de se conectar com os outros. Esse aspecto cria um fluxo suave de energia entre a Lua, que representa as emoções e o eu interior, e o Ascendente, que governa a personalidade, a aparência e as primeiras impressões."}],"Expressão Emocional":[{"type":"p","content":"Indivíduos com esse aspecto são frequentemente emocionalmente sintonizados com seu entorno. Eles têm uma capacidade natural de expressar seus sentimentos de uma maneira que ressoa com os outros, tornando-os acessíveis e empáticos. Sua inteligência emocional é alta, permitindo que naveguem em situações sociais com facilidade e graça."}],"Relacionamentos e Interações":[{"type":"p","content":"Pessoas com a Lua em trígono com o Ascendente são frequentemente vistas como nutridoras e solidárias. Elas têm um talento para fazer os outros se sentirem confortáveis e compreendidos. Nos relacionamentos, são parceiros atenciosos e cuidadosos que priorizam a conexão emocional e o entendimento mútuo."}],"Autoimagem e Confiança":[{"type":"p","content":"Esse aspecto também influencia positivamente a autoimagem. Esses indivíduos tendem a ter um senso saudável de autoestima e confiança. Eles estão confortáveis em sua própria pele e projetam uma sensação de paz interior e estabilidade, o que pode ser muito atraente para os outros."}],"Desafios e Crescimento":[{"type":"p","content":"Embora a Lua em trígono com o Ascendente seja geralmente um aspecto benéfico, às vezes pode levar a uma dependência excessiva da intuição emocional. Os indivíduos podem precisar equilibrar suas respostas emocionais com o pensamento lógico para evitar se tornarem excessivamente sensíveis ou dependentes da aprovação dos outros."}],"Conclusão":[{"type":"p","content":"A Lua em trígono com o Ascendente é um aspecto poderoso que promove harmonia emocional, fortes conexões interpessoais e uma autoimagem positiva. Ao abraçar sua natureza intuitiva enquanto mantêm uma abordagem equilibrada em relação às emoções, os indivíduos com esse aspecto podem prosperar tanto no âmbito pessoal quanto no social."}]}',
  },
  {
    aspectingPlanet: 'jupiter',
    aspectedPlanet: 'pluto',
    type: 'square',
    orb: 5.46,
    diff: 95.46,
    report: null,
  },
  {
    aspectingPlanet: 'mars',
    aspectedPlanet: 'ascendant',
    type: 'trine',
    orb: 1.65,
    diff: 118.35,
    report: null,
  },
  {
    aspectingPlanet: 'mercury',
    aspectedPlanet: 'uranus',
    type: 'conjunction',
    orb: 0.02,
    diff: 0.02,
    report:
      '{"Visão Geral":[{"type":"p","content":"A conjunção entre Mercúrio e Urano é um aspecto astrológico poderoso que une as características analíticas e comunicativas de Mercúrio com a energia revolucionária e imprevisível de Urano. Esse alinhamento estimula um período de intensa atividade mental, originalidade e pensamento não convencional, trazendo insights repentinos, avanços e um desejo de liberdade intelectual."}],"Temas Principais":[{"type":"bullet-point","title":"Agilidade Mental e Inovação","content":"Esse aspecto estimula a mente, incentivando ideias inovadoras e soluções criativas para problemas. É um momento em que pensar fora da caixa se torna natural, e métodos convencionais podem parecer limitantes."},{"type":"bullet-point","title":"Comunicação Imprevisível","content":"A comunicação pode se tornar errática ou repentina, com uma tendência a expressar ideias não convencionais ou radicais. Isso pode levar a trocas emocionantes, mas também pode causar mal-entendidos se não for equilibrada com clareza."},{"type":"bullet-point","title":"Foco em Tecnologia e Ciência","content":"Urano rege a tecnologia e o progresso, então essa conjunção frequentemente destaca avanços nessas áreas. É um momento favorável para explorar novas tecnologias, descobertas científicas ou inovações digitais."},{"type":"bullet-point","title":"Liberdade de Pensamento","content":"Há um forte desejo de independência intelectual e liberdade das restrições tradicionais. As pessoas podem se sentir compelidas a desafiar normas, questionar autoridades ou adotar pontos de vista progressistas."}],"Impacto nos Indivíduos":[{"type":"p","content":"Para os indivíduos, essa conjunção pode se manifestar como uma explosão repentina de inspiração ou uma necessidade de romper com a rotina. É um momento para abraçar mudanças, experimentar novas ideias e se comunicar com ousadia. No entanto, é importante permanecer centrado para evitar impulsividade ou pensamento disperso."}],"Impacto nos Relacionamentos":[{"type":"p","content":"Nos relacionamentos, esse aspecto pode trazer conversas emocionantes e inesperadas. Os parceiros podem se sentir mais abertos para discutir tópicos não convencionais ou explorar novas formas de conexão. No entanto, tensões podem surgir se as ideias de uma pessoa parecerem muito radicais ou imprevisíveis para a outra."}],"Dicas para Aproveitar Essa Energia":[{"type":"bullet-point","content":"Abrace a curiosidade e explore novas ideias."},{"type":"bullet-point","content":"Esteja aberto a insights repentinos ou mudanças de perspectiva."},{"type":"bullet-point","content":"Comunique-se com clareza para evitar mal-entendidos."},{"type":"bullet-point","content":"Use a tecnologia ou ferramentas inovadoras para aumentar a produtividade."}],"Conclusão":[{"type":"p","content":"A conjunção entre Mercúrio e Urano é um aspecto dinâmico e transformador que incentiva a liberdade intelectual, a inovação e o progresso. Ao abraçar sua energia, você pode desbloquear novas possibilidades e expandir seus horizontes."}]}',
  },
  {
    aspectingPlanet: 'mars',
    aspectedPlanet: 'saturn',
    type: 'trine',
    orb: 7.76,
    diff: 127.76,
    report: null,
  },
  {
    aspectingPlanet: 'mercury',
    aspectedPlanet: 'neptune',
    type: 'conjunction',
    orb: 4.85,
    diff: 4.85,
    report:
      '{"Visão Geral":[{"type":"p","content":"A conjunção Mercúrio-Netuno é um aspecto astrológico fascinante que combina as energias da comunicação (Mercúrio) e da intuição, imaginação e espiritualidade (Netuno). Esse alinhamento cria uma interação única entre lógica e criatividade, muitas vezes ampliando a expressão artística, a empatia e a sensibilidade psíquica. No entanto, também pode trazer desafios, como confusão, má comunicação ou uma tendência a escapar da realidade."}],"Temas Principais":[{"type":"bullet-point","title":"Imaginação e Criatividade Aprimoradas","content":"Esse aspecto amplia as habilidades criativas, tornando-o um excelente momento para atividades artísticas, escrita ou qualquer forma de expressão pessoal."},{"type":"bullet-point","title":"Comunicação Intuitiva","content":"Mercúrio conjunção Netuno pode aumentar a intuição, permitindo que os indivíduos percebam sinais sutis e se comuniquem com empatia e sensibilidade."},{"type":"bullet-point","title":"Potencial para Confusão","content":"A mistura da lógica de Mercúrio com o sonho de Netuno pode levar a mal-entendidos, pensamentos vagos ou dificuldade em distinguir fato de ficção."},{"type":"bullet-point","title":"Insights Espirituais","content":"Essa conjunção frequentemente promove uma conexão mais profunda com a espiritualidade, meditação ou experiências místicas."}],"Manifestações Positivas":[{"type":"bullet-point","title":"Inspiração Artística","content":"Escritores, artistas e músicos podem encontrar seu trabalho impregnado de ideias profundas e imaginativas."},{"type":"bullet-point","title":"Empatia e Compaixão","content":"As conversas se tornam mais sinceras, e os indivíduos podem se sentir mais sintonizados com as emoções dos outros."},{"type":"bullet-point","title":"Sensibilidade Psíquica","content":"A intuição aumentada pode levar a sonhos proféticos, fortes intuições ou revelações espirituais."}],"Desafios a Considerar":[{"type":"bullet-point","title":"Má Comunicação","content":"As mensagens podem ser pouco claras ou mal interpretadas, levando a confusão em relacionamentos pessoais ou profissionais."},{"type":"bullet-point","title":"Evasão","content":"O desejo de se refugiar em um mundo de fantasia pode se tornar avassalador, potencialmente negligenciando responsabilidades."},{"type":"bullet-point","title":"Engano","content":"Esse aspecto pode aumentar a suscetibilidade a enganos, seja de outras pessoas ou de autoengano."}],"Conselhos Práticos":[{"type":"bullet-point","title":"Clarifique as Intenções","content":"Esteja atento à sua comunicação, garantindo que sua mensagem seja clara e compreendida."},{"type":"bullet-point","title":"Aterre-se","content":"Pratique atividades de aterramento, como meditação ou passar tempo na natureza, para permanecer conectado à realidade."},{"type":"bullet-point","title":"Canalize a Criatividade","content":"Use essa energia de forma construtiva, engajando-se em atividades artísticas ou espirituais que o inspirem."}],"Conclusão":[{"type":"p","content":"A conjunção Mercúrio-Netuno é um aspecto poderoso que une os domínios da lógica e da intuição. Embora ofereça um potencial criativo e espiritual imenso, também exige atenção para superar seus desafios. Ao abraçar seus presentes e permanecer aterrado, esse alinhamento pode levar a um profundo crescimento pessoal e inspiração."}]}',
  },
  {
    aspectingPlanet: 'venus',
    aspectedPlanet: 'midheaven',
    type: 'sextile',
    orb: 0.31,
    diff: 59.69,
    report: null,
  },
  {
    aspectingPlanet: 'saturn',
    aspectedPlanet: 'neptune',
    type: 'conjunction',
    orb: 9.95,
    diff: 9.95,
    report: null,
  },
  {
    aspectingPlanet: 'saturn',
    aspectedPlanet: 'pluto',
    type: 'sextile',
    orb: 4.39,
    diff: 64.39,
    report: null,
  },
  {
    aspectingPlanet: 'uranus',
    aspectedPlanet: 'neptune',
    type: 'conjunction',
    orb: 4.87,
    diff: 4.87,
    report: null,
  },
  {
    aspectingPlanet: 'saturn',
    aspectedPlanet: 'midheaven',
    type: 'square',
    orb: 4.75,
    diff: 85.25,
    report: null,
  },
  {
    aspectingPlanet: 'saturn',
    aspectedPlanet: 'ascendant',
    type: 'conjunction',
    orb: 9.41,
    diff: 9.41,
    report: null,
  },
  {
    aspectingPlanet: 'neptune',
    aspectedPlanet: 'pluto',
    type: 'sextile',
    orb: 5.56,
    diff: 54.44,
    report: null,
  },
  {
    aspectingPlanet: 'ascendant',
    aspectedPlanet: 'midheaven',
    type: 'square',
    orb: 4.66,
    diff: 94.66,
    report: null,
  },
];

export default mockAspectsData;
